import { QuartzEmitterPlugin } from "../types"
import { write } from "./helpers"
import { FullSlug, joinSegments } from "../../util/path"

export interface PWAOptions {
  /** Short name shown under the installed app icon */
  shortName?: string
  /** Background colour of the splash screen */
  backgroundColor: string
  /** Colour of the OS toolbar */
  themeColor: string
}

const defaultOptions: PWAOptions = {
  backgroundColor: "#faf8f8",
  themeColor: "#284b63",
}

/** base path the site is served from, e.g. "/obsidian-notes/" for a project page */
export function basePathFromBaseUrl(baseUrl?: string): string {
  if (!baseUrl) return "/"
  const { pathname } = new URL(`https://${baseUrl.replace(/^https?:\/\//, "")}`)
  return pathname.endsWith("/") ? pathname : `${pathname}/`
}

const serviceWorker = (base: string, version: string) => `// generated by Quartz PWA emitter
const VERSION = "${version}"
const CACHE = "quartz-" + VERSION
const BASE = "${base}"
const OFFLINE = BASE + "404.html"

const INDEX = BASE + "static/contentIndex.json"
const PRECACHE_BATCH = 6

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll([BASE, OFFLINE])).then(() => self.skipWaiting()),
  )
})

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
      .then(() => precacheAll()),
  )
})

// Pull every note into the cache so the whole garden is readable offline,
// not just the pages that happen to have been visited.
let precaching = null
function precacheAll() {
  if (precaching) return precaching
  precaching = (async () => {
    try {
      const cache = await caches.open(CACHE)
      const res = await fetch(INDEX, { cache: "no-cache" })
      if (!res.ok) return
      const index = await res.json()
      // notes, plus every auto-generated folder page and tag page reachable from them —
      // breadcrumbs and tag chips navigate to these, so offline needs them too
      const urlSet = new Set([INDEX])
      for (const slug of Object.keys(index)) {
        urlSet.add(BASE + slug)
        const parts = slug.split("/")
        for (let i = 1; i < parts.length; i++) urlSet.add(BASE + parts.slice(0, i).join("/") + "/")
        for (const tag of index[slug].tags ?? []) {
          const segs = String(tag).split("/")
          for (let i = 1; i <= segs.length; i++)
            urlSet.add(BASE + "tags/" + segs.slice(0, i).join("/"))
        }
        urlSet.add(BASE + "tags/")
      }
      const urls = [...urlSet]
      let done = 0
      for (let i = 0; i < urls.length; i += PRECACHE_BATCH) {
        await Promise.all(
          urls.slice(i, i + PRECACHE_BATCH).map(async (url) => {
            try {
              const target = url.endsWith(".json")
                ? url
                : url.endsWith("/")
                  ? url + "index.html"
                  : url + ".html"
              const hit = await fetch(target)
              if (hit.ok) await cachePage(cache, url, hit)
            } catch {
              // one missing page shouldn't abort the whole pass
            }
          }),
        )
        done += PRECACHE_BATCH
        await broadcast({ type: "precache-progress", done: Math.min(done, urls.length), total: urls.length })
      }
      await broadcast({ type: "precache-done", total: urls.length })
    } finally {
      precaching = null
    }
  })()
  return precaching
}

// Pages are requested three different ways: as a navigation to "/slug", as an
// SPA fetch of "/slug", and (by us) as "/slug.html". Store every variant so an
// offline lookup hits regardless of which form the request takes.
async function cachePage(cache, url, response) {
  let keys
  if (url.endsWith(".json")) keys = [url]
  else if (url.endsWith("/")) keys = [url, url + "index.html"]
  else {
    keys = [url, url + ".html"]
    if (url.endsWith("/index")) keys.push(url.slice(0, -"index".length))
  }
  const bodies = keys.map(() => response.clone())
  await Promise.all(keys.map((key, i) => cache.put(key, bodies[i])))
}

// try every URL variant a page might be cached under
async function matchPage(request) {
  const url = new URL(request.url)
  const candidates = [request, url.pathname]
  if (!url.pathname.endsWith(".html")) {
    candidates.push(url.pathname + ".html")
    if (url.pathname.endsWith("/")) candidates.push(url.pathname + "index.html")
  }
  for (const candidate of candidates) {
    const hit = await caches.match(candidate, { ignoreSearch: true })
    if (hit) return hit
  }
  return undefined
}

async function broadcast(msg) {
  const clients = await self.clients.matchAll({ type: "window" })
  for (const client of clients) client.postMessage(msg)
}

self.addEventListener("message", (event) => {
  if (event.data === "precache-all") event.waitUntil(precacheAll())
})

// only ever cache same-origin GETs that live under our base path
function isCacheable(url) {
  return url.origin === self.location.origin && url.pathname.startsWith(BASE)
}

self.addEventListener("fetch", (event) => {
  const req = event.request
  if (req.method !== "GET") return
  const url = new URL(req.url)
  if (!isCacheable(url)) return

  // navigations: network first so notes stay fresh, cache as offline fallback
  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req)
        .then((res) => {
          // never cache error pages — a cached 404 would shadow the real page later
          if (res.ok) {
            const copy = res.clone()
            caches.open(CACHE).then((cache) => cache.put(req, copy))
          }
          return res
        })
        .catch(() => matchPage(req).then((hit) => hit ?? caches.match(OFFLINE))),
    )
    return
  }

  // assets: stale-while-revalidate
  event.respondWith(
    matchPage(req).then((hit) => {
      const fetching = fetch(req)
        .then((res) => {
          if (res.ok) {
            const copy = res.clone()
            caches.open(CACHE).then((cache) => cache.put(req, copy))
          }
          return res
        })
        .catch(() => hit)
      return hit ?? fetching
    }),
  )
})
`

export const PWA: QuartzEmitterPlugin<Partial<PWAOptions>> = (userOpts) => {
  const opts = { ...defaultOptions, ...userOpts }
  return {
    name: "PWA",
    async emit(ctx) {
      const cfg = ctx.cfg.configuration
      const base = basePathFromBaseUrl(cfg.baseUrl)
      const manifest = {
        name: cfg.pageTitle,
        short_name: opts.shortName ?? cfg.pageTitle,
        description: `${cfg.pageTitle} — a Quartz digital garden`,
        start_url: base,
        scope: base,
        display: "standalone",
        orientation: "any",
        background_color: opts.backgroundColor,
        theme_color: opts.themeColor,
        lang: cfg.locale?.split("-")[0] ?? "en",
        icons: [
          {
            src: joinSegments(base, "static/icon-192.png"),
            sizes: "192x192",
            type: "image/png",
            purpose: "any",
          },
          {
            src: joinSegments(base, "static/icon-512.png"),
            sizes: "512x512",
            type: "image/png",
            purpose: "any",
          },
          {
            src: joinSegments(base, "static/icon-512.png"),
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      }

      // bust the cache whenever the build changes
      const version = ctx.buildId

      return [
        await write({
          ctx,
          content: JSON.stringify(manifest, null, 2),
          slug: "manifest" as FullSlug,
          ext: ".webmanifest",
        }),
        await write({
          ctx,
          content: serviceWorker(base, version),
          slug: "sw" as FullSlug,
          ext: ".js",
        }),
      ]
    },
    async *partialEmit() {},
  }
}
